# BikeToDrive_SDM

### 1. Maak eerst in de folder 'databases/' "BikeToDrive_SDM.db" aan in SQLite-Browser
### 2. Implementeer nu het RIM met de inhoud van het 'SDM-RIM.txt' bestand in de db browser.
### 3. Zorg dat alle 5 databases van School in dezelfde 'databases/' map staan.
### 4. Voer nu alle Python script below uit.

![Klassendiagram_SDM](SDM_diagram.png)

In [1]:
import pandas as pd
import sqlite3
from sqlalchemy import create_engine
import os
from sqlalchemy import text

db_path = "databases/"

sdm_engine = create_engine(f'sqlite:///{db_path}BikeToDrive_SDM.db')

In [11]:
e1 = create_engine(f'sqlite:///{db_path}BikeToDrive_1_Accessoireverkoop.db')
e2 = create_engine(f'sqlite:///{db_path}BikeToDrive_2_Fietsverkoop.db')
e3 = create_engine(f'sqlite:///{db_path}BikeToDrive_3_Onderhoud.db')
e4 = create_engine(f'sqlite:///{db_path}BikeToDrive_4_Accessoire_Inkoop.db')
e5 = create_engine(f'sqlite:///{db_path}BikeToDrive_5_Fiets_Inkoop.db')
# --- 1. Accessoireverkoop ---
Accessoireverkoop_Leverancier = pd.read_sql("SELECT * FROM Leverancier", e1)
Accessoireverkoop_Accessoire = pd.read_sql("SELECT * FROM Accessoire", e1)
Accessoireverkoop_Filiaal = pd.read_sql("SELECT * FROM Filiaal", e1)
Accessoireverkoop_Monteur = pd.read_sql("SELECT * FROM Monteur", e1)
Accessoireverkoop_Klant = pd.read_sql("SELECT * FROM Klant", e1)
Accessoire_Verkoop = pd.read_sql("SELECT * FROM Accessoire_Verkoop", e1)

# --- 2. Fietsverkoop ---
Fietsverkoop_Fabrikant = pd.read_sql("SELECT * FROM Fabrikant", e2)
Fietsverkoop_Fiets = pd.read_sql("SELECT * FROM Fiets", e2)
Fietsverkoop_Filiaal = pd.read_sql("SELECT * FROM Filiaal", e2)
Fietsverkoop_Monteur = pd.read_sql("SELECT * FROM Monteur", e2)
Fietsverkoop_Klant = pd.read_sql("SELECT * FROM Klant", e2)
Fiets_Verkoop = pd.read_sql("SELECT * FROM Fiets_Verkoop", e2)

# --- 3. Onderhoud ---
Onderhoud_Fabrikant = pd.read_sql("SELECT * FROM Fabrikant", e3)
Onderhoud_Fiets = pd.read_sql("SELECT * FROM Fiets", e3)
Onderhoud_Filiaal = pd.read_sql("SELECT * FROM Filiaal", e3)
Onderhoud_Monteur = pd.read_sql("SELECT * FROM Monteur", e3)
Onderhoud = pd.read_sql("SELECT * FROM Onderhoud", e3)

# --- 4. Accessoire Inkoop ---
Accessoire_Inkoop_Leverancier = pd.read_sql("SELECT * FROM Leverancier", e4)
Accessoire_Inkoop_Accessoire = pd.read_sql("SELECT * FROM Accessoire", e4)
Accessoire_Inkoop = pd.read_sql("SELECT * FROM Accessoire_Inkoop", e4)

# --- 5. Fiets Inkoop ---
Fiets_Inkoop_Fabrikant = pd.read_sql("SELECT * FROM Fabrikant", e5)
Fiets_Inkoop_Fiets = pd.read_sql("SELECT * FROM Fiets", e5)
Fiets_Inkoop = pd.read_sql("SELECT * FROM Fiets_Inkoop", e5)

In [13]:
export_lijst = [
    (Accessoireverkoop_Leverancier, 'Accessoireverkoop_Leverancier'),
    (Accessoireverkoop_Filiaal, 'Accessoireverkoop_Filiaal'),
    (Accessoireverkoop_Klant, 'Accessoireverkoop_Klant'),
    (Fietsverkoop_Fabrikant, 'Fietsverkoop_Fabrikant'),
    (Fietsverkoop_Filiaal, 'Fietsverkoop_Filiaal'),
    (Fietsverkoop_Klant, 'Fietsverkoop_Klant'),
    (Onderhoud_Fabrikant, 'Onderhoud_Fabrikant'),
    (Onderhoud_Filiaal, 'Onderhoud_Filiaal'),
    (Accessoire_Inkoop_Leverancier, 'Accessoire_Inkoop_Leverancier'),
    (Fiets_Inkoop_Fabrikant, 'Fiets_Inkoop_Fabrikant'),
    (Accessoireverkoop_Accessoire, 'Accessoireverkoop_Accessoire'),
    (Accessoireverkoop_Monteur, 'Accessoireverkoop_Monteur'),
    (Fietsverkoop_Fiets, 'Fietsverkoop_Fiets'),
    (Fietsverkoop_Monteur, 'Fietsverkoop_Monteur'),
    (Onderhoud_Fiets, 'Onderhoud_Fiets'),
    (Onderhoud_Monteur, 'Onderhoud_Monteur'),
    (Accessoire_Inkoop_Accessoire, 'Accessoire_Inkoop_Accessoire'),
    (Fiets_Inkoop_Fiets, 'Fiets_Inkoop_Fiets'),
    (Accessoire_Verkoop, 'Accessoire_Verkoop'),
    (Fiets_Verkoop, 'Fiets_Verkoop'),
    (Onderhoud, 'Onderhoud'),
    (Accessoire_Inkoop, 'Accessoire_Inkoop'),
    (Fiets_Inkoop, 'Fiets_Inkoop')
]

In [ ]:

with sdm_engine.begin() as conn:
    print("Start de Full-Refresh op het SDM")

    for df, tabelnaam in export_lijst:
        try:
            conn.execute(text(f"DELETE FROM {tabelnaam}"))

            df.to_sql(tabelnaam, con=conn, if_exists='append', index=False)

            print(f"{tabelnaam}: {len(df)} rijen succesvol geladen.")

        except Exception as e:
            print(f"Fout bij {tabelnaam}: {e}")

print("Full-Refresh voltooid.")

Start de Full-Refresh op het SDM
Accessoireverkoop_Leverancier: 5 rijen succesvol geladen.
Accessoireverkoop_Filiaal: 4 rijen succesvol geladen.
Accessoireverkoop_Klant: 20 rijen succesvol geladen.
Fietsverkoop_Fabrikant: 10 rijen succesvol geladen.
Fietsverkoop_Filiaal: 4 rijen succesvol geladen.
Fietsverkoop_Klant: 25 rijen succesvol geladen.
Onderhoud_Fabrikant: 11 rijen succesvol geladen.
Onderhoud_Filiaal: 5 rijen succesvol geladen.
Accessoire_Inkoop_Leverancier: 5 rijen succesvol geladen.
Fiets_Inkoop_Fabrikant: 10 rijen succesvol geladen.
Accessoireverkoop_Accessoire: 10 rijen succesvol geladen.
Accessoireverkoop_Monteur: 10 rijen succesvol geladen.
Fietsverkoop_Fiets: 75 rijen succesvol geladen.
Fietsverkoop_Monteur: 10 rijen succesvol geladen.
Onderhoud_Fiets: 30 rijen succesvol geladen.
Onderhoud_Monteur: 15 rijen succesvol geladen.
Accessoire_Inkoop_Accessoire: 13 rijen succesvol geladen.
Fiets_Inkoop_Fiets: 75 rijen succesvol geladen.
Accessoire_Verkoop: 100 rijen succesvol geladen.
Fiets_Verkoop: 150 rijen succesvol geladen.
Onderhoud: 50 rijen succesvol geladen.
Accessoire_Inkoop: 50 rijen succesvol geladen.
Fiets_Inkoop: 100 rijen succesvol geladen.
Full-Refresh voltooid.

In [6]:
acc_fil = pd.read_sql("select * from accessoireverkoop_filiaal", sdm_engine)
onderhoud_fil = pd.read_sql("SELECT * FROM onderhoud_filiaal", sdm_engine)
fiets_fil = pd.read_sql("select * from fietsverkoop_filiaal", sdm_engine)

# accessoirefiliaal 1 <-filiaalnr-> 1 fiets_filiaal
diff = pd.merge(
    acc_fil, 
    fiets_fil, 
    on='filiaalnr', 
    how='outer', 
    indicator=False,
    suffixes=('_acc', '_fiets')
    )

#acc_fil & fiets_filiaal 0..1 <-filiaalnr-> 1 onderhoud_filiaal
nextdiff = pd.merge(
    diff, 
    onderhoud_fil, 
    on='filiaalnr', 
    how='outer', 
    indicator=True,
    suffixes=('_diff', '_onderhoud')
    )

nextdiff

,filiaalnr,naam_acc,adres_acc,provincie_acc,naam_fiets,adres_fiets,provincie_fiets,naam,adres,provincie,_merge
0,1,BikeWorld Amsterdam,Prinsengracht 100,Noord-Holland,BikeWorld Amsterdam,Prinsengracht 100,Noord-Holland,BikeWorld Amsterdam,Prinsengracht 100,Noord-Holland,both
1,2,FietsGigant Haarlem,Grote Markt 22,Noord-Holland,FietsGigant Haarlem,Grote Markt 22,Noord-Holland,FietsGigant Haarlem,Grote Markt 22,Noord-Holland,both
2,3,FietsExpress Rotterdam,Coolsingel 55,Zuid-Holland,FietsExpress Rotterdam,Coolsingel 55,Zuid-Holland,FietsExpress Rotterdam,Coolsingel 55,Zuid-Holland,both
3,4,CycleCity Leiden,Breestraat 48,Zuid-Holland,CycleCity Leiden,Breestraat 48,Zuid-Holland,CycleCity Leiden,Breestraat 48,Zuid-Holland,both
4,5,NaN,NaN,NaN,NaN,NaN,NaN,ZaanFiets Zaandam,Damstraat 5,Noord-Holland,right_only

In [12]:

fiets_mont = pd.read_sql("select * from fietsverkoop_monteur", sdm_engine)
acc_mont = pd.read_sql("select * from accessoireverkoop_monteur", sdm_engine)
onderhoud_mont = pd.read_sql("SELECT * FROM onderhoud_monteur", sdm_engine)
# accessoireverkoop_monteur 1 <-monteurnr-> 1 fietsverkoop_monteur
diff = pd.merge(
    acc_mont, 
    fiets_mont, 
    on='monteurnr', 
    how='outer', 
    indicator=False,
    suffixes=('_acc', '_fiets')
    )
# acc_mont & fiets_month 0..1 <-monteurnr-> 1 onderhoud_monteur
nextdiff = pd.merge(
    diff, 
    onderhoud_mont, 
    on='monteurnr', 
    how='outer', 
    indicator=True,
    suffixes=('_diff', '_onderhoud')
    )

nextdiff

,monteurnr,naam_acc,woonplaats_acc,uurloon_acc,filiaal_acc,naam_fiets,woonplaats_fiets,uurloon_fiets,filiaal_fiets,naam,woonplaats,uurloon,filiaal,_merge
0,1,Tom van Dijk,Amsterdam,19.50,1.0,Tom van Dijk,Amsterdam,19.50,1.0,Tom van Dijk,Amsterdam,19.50,1,both
1,2,Lisa Verhoeven,Amstelveen,18.75,1.0,Lisa Verhoeven,Amstelveen,18.75,1.0,Lisa Verhoeven,Amstelveen,18.75,1,both
2,3,Kevin Jaspers,Zaandam,20.00,1.0,Kevin Jaspers,Zaandam,20.00,1.0,Kevin Jaspers,Zaandam,20.00,1,both
3,4,Romy Willems,Haarlem,17.80,2.0,Romy Willems,Haarlem,17.80,2.0,Romy Willems,Haarlem,17.80,2,both
4,5,Daan de Groot,Rotterdam,21.00,3.0,Daan de Groot,Rotterdam,21.00,3.0,Daan de Groot,Rotterdam,21.00,3,both
5,6,Sophie de Leeuw,Schiedam,19.90,3.0,Sophie de Leeuw,Schiedam,19.90,3.0,Sophie de Leeuw,Schiedam,19.90,3,both
6,7,Mark van Vliet,Dordrecht,20.25,3.0,Mark van Vliet,Dordrecht,20.25,3.0,Mark van Vliet,Dordrecht,20.25,3,both
7,8,Jesse Peters,Leiden,16.95,4.0,Jesse Peters,Leiden,16.95,4.0,Jesse Peters,Leiden,16.95,4,both
8,9,Eva Meijer,Zoetermeer,18.40,4.0,Eva Meijer,Zoetermeer,18.40,4.0,Eva Meijer,Zoetermeer,18.40,4,both
9,10,Milan de Bruin,Zaandam,17.25,2.0,Milan de Bruin,Zaandam,17.25,2.0,Milan de Bruin,Zaandam,17.25,5,both
10,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sara de Koning,Haarlem,19.20,1,right_only
11,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Nick Smits,Rotterdam,20.50,1,right_only
12,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Laura Smeets,Amsterdam,18.80,1,right_only
13,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Pim Scholten,Leiden,17.90,5,right_only
14,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Tijn Hendriks,Zaandam,17.10,5,right_only

In [10]:
aklant = pd.read_sql("select * from accessoireverkoop_klant", sdm_engine)
fklant = pd.read_sql("SELECT * FROM fietsverkoop_klant", sdm_engine)

diff = pd.merge(aklant, fklant, on='klantnr', how='outer', indicator=True, suffixes=('_a', '_f'))
diff

,klantnr,naam_a,adres_a,woonplaats_a,geslacht_a,geboortedatum_a,naam_f,adres_f,woonplaats_f,geslacht_f,geboortedatum_f,_merge
0,1,Jan Jansen,Kerkstraat 12,Amsterdam,M,1985-03-22,Jan Jansen,Kerkstraat 12,Amsterdam,M,1985-03-22,both
1,2,Sophie de Boer,Lindelaan 8,Rotterdam,V,1990-07-11,Sophie de Boer,Lindelaan 8,Rotterdam,V,1990-07-11,both
2,3,Pieter Visser,Havenstraat 3,Den Haag,M,1978-11-05,Pieter Visser,Havenstraat 3,Den Haag,M,1978-11-05,both
3,4,Emma Smit,Boomgaard 22,Haarlem,V,1995-02-18,Emma Smit,Boomgaard 22,Haarlem,V,1995-02-18,both
4,5,Tom Bakker,Stationsweg 44,Leiden,M,1982-09-09,Tom Bakker,Stationsweg 44,Leiden,M,1982-09-09,both
5,6,Lisa Meijer,Dijkstraat 10,Zaandam,V,1993-12-30,Lisa Meijer,Dijkstraat 10,Zaandam,V,1993-12-30,both
6,7,Bart de Vries,Brouwersgracht 7,Delft,M,1976-06-06,Bart de Vries,Brouwersgracht 7,Delft,M,1976-06-06,both
7,8,Julia van Dijk,Plataanlaan 5,Hoorn,V,2000-01-15,Julia van Dijk,Plataanlaan 5,Hoorn,V,2000-01-15,both
8,9,Kevin Mol,Singel 99,Alkmaar,M,1989-08-01,Kevin Mol,Singel 99,Alkmaar,M,1989-08-01,both
9,10,Nina Groen,Waterstraat 16,Schiedam,V,1991-05-25,Nina Groen,Waterstraat 16,Schiedam,V,1991-05-25,both
10,11,Daan Willems,Parklaan 31,Haarlem,M,1987-10-12,Daan Willems,Parklaan 31,Haarlem,M,1987-10-12,both
11,12,Eva Vos,Zomerweg 2,Zoetermeer,V,1996-04-03,Eva Vos,Zomerweg 2,Zoetermeer,V,1996-04-03,both
12,13,Rik de Jong,Noorderstraat 88,Hilversum,M,1980-12-21,Rik de Jong,Noorderstraat 88,Hilversum,M,1980-12-21,both
13,14,Mila Kuipers,Heemraadssingel 15,Rotterdam,V,1998-09-17,Mila Kuipers,Heemraadssingel 15,Rotterdam,V,1998-09-17,both
14,15,Sam Reinders,Beethovenlaan 13,Haarlem,M,1983-01-29,Sam Reinders,Beethovenlaan 13,Haarlem,M,1983-01-29,both
15,16,Fleur Schouten,Tulpenstraat 5,Amsterdam,V,1994-06-08,Robin Dekker,Rozenstraat 4,Delft,M,1992-11-23,both
16,17,Lars van den Berg,Kade 101,Leiden,M,1988-03-02,Lieke de Wit,Tulpenpad 19,Den Haag,V,1986-07-12,both
17,18,Tess van Leeuwen,Markt 22,Dordrecht,V,1997-07-19,Jeroen Hermans,Klaprooslaan 6,Zaandam,M,1999-05-04,both
18,19,Jesse van Dam,Zuidlaan 7,Alphen aan den Rijn,M,1981-11-27,Tessa van Vliet,Nieuwstraat 12,Leiden,V,2001-03-18,both
19,20,Noa Blom,Vondelstraat 18,Zaandam,V,2002-02-10,Bas Hendriks,IJsselstraat 2,Rotterdam,M,1984-10-30,both
20,21,NaN,NaN,NaN,NaN,NaN,Luna Hoekstra,Hortensialaan 1,Amstelveen,V,1997-08-07,right_only
21,22,NaN,NaN,NaN,NaN,NaN,Noah de Groot,Burgemeesterlaan 9,Haarlem,M,1990-12-02,right_only
22,23,NaN,NaN,NaN,NaN,NaN,Amber Peeters,Merellaan 18,Hoofddorp,V,1995-06-21,right_only
23,24,NaN,NaN,NaN,NaN,NaN,Mats Jonker,Kasteelstraat 7,Schiedam,M,1988-01-05,right_only
24,25,NaN,NaN,NaN,NaN,NaN,Isis Mulder,Goudenregenstraat 11,Dordrecht,V,2000-09-28,right_only

In [ ]:
ilev = pd.read_sql("select * from accessoire_inkoop_leverancier", sdm_engine)
vlev = pd.read_sql("SELECT * FROM accessoireverkoop_leverancier", sdm_engine)

diff = pd.merge(ilev, vlev, on='leveranciernr', how='outer', indicator=True, suffixes=('_i', '_v'))
diff

,leveranciernr,naam_i,adres_i,woonplaats_i,naam_v,adres_v,woonplaats_v,_merge
0,1,BikeParts BV,Fietsenstraat 12,Amsterdam,BikeParts BV,Fietsenstraat 12,Amsterdam,both
1,2,CycleSupplies,Rembrandtlaan 7,Rotterdam,CycleSupplies,Rembrandtlaan 7,Rotterdam,both
2,3,TwoWheels Trading,Marktplein 5,Den Haag,TwoWheels Trading,Marktplein 5,Den Haag,both
3,4,DutchBike Import,Kade 22,Leiden,DutchBike Import,Kade 22,Leiden,both
4,5,UrbanGear NL,Stationsweg 15,Utrecht,UrbanGear NL,Stationsweg 15,Utrecht,both

In [16]:
ifab = pd.read_sql("select * from fiets_inkoop_fabrikant", sdm_engine)
vfab = pd.read_sql("SELECT * FROM fietsverkoop_fabrikant", sdm_engine)

diff2 = pd.merge(ifab, vfab, on='fabrikantnr', how='outer', indicator=True, suffixes=('_i', '_v'))
diff2

,fabrikantnr,naam_i,adres_i,plaats_i,naam_v,adres_v,plaats_v,_merge
0,1,SpeedCycle BV,Spoorstraat 12,Eindhoven,SpeedCycle BV,Spoorstraat 12,Eindhoven,both
1,2,UrbanBike Co.,Keizersgracht 45,Amsterdam,UrbanBike Co.,Keizersgracht 45,Amsterdam,both
2,3,HollandRider,Marktstraat 9,Utrecht,HollandRider,Marktstraat 9,Utrecht,both
3,4,EcoWheelers,Kade 33,Delft,EcoWheelers,Kade 33,Delft,both
4,5,DutchMotion,Westplein 7,Rotterdam,DutchMotion,Westplein 7,Rotterdam,both
5,6,NordicBike,Prinsestraat 18,Groningen,NordicBike,Prinsestraat 18,Groningen,both
6,7,CycleTech,Boslaan 60,Den Haag,CycleTech,Boslaan 60,Den Haag,both
7,8,GreenGear,Leliestraat 24,Nijmegen,GreenGear,Leliestraat 24,Nijmegen,both
8,9,FastFrame,Rivierlaan 3,Maastricht,FastFrame,Rivierlaan 3,Maastricht,both
9,10,OranjeFiets,Brink 88,Zwolle,OranjeFiets,Brink 88,Zwolle,both